### ISSUE TITLE
Repo readme does not work anymore

### ISSUE THREAD

**Issue by ChrisMoriarty** [dataprofessor/streamlit_navbar#2]
Followed your instructions, and I end up getting the following error:

```
(streamlit_navbar) ~/streamlit_navbar-main $ streamlit run app_navbar.py
Traceback (most recent call last):
  File "/Users/cmoriarty/opt/miniconda3/envs/streamlit_navbar/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/Users/cmoriarty/opt/miniconda3/envs/streamlit_navbar/lib/python3.7/site-packages/streamlit/__init__.py", line 48, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "/Users/cmoriarty/opt/miniconda3/envs/streamlit_navbar/lib/python3.7/site-packages/streamlit/proto/RootContainer_pb2.py", line 37, in <module>
    create_key=_descriptor._internal_create_key),
  File "/Users/cmoriarty/opt/miniconda3/envs/streamlit_navbar/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
I also just copied the app's code into my own newer conda env, which did work, but doesn't actually display the top bar:
<img width="762" alt="image" src="https://github.com/dataprofessor/streamlit_navbar/assets/422237/93d19a0f-cf2e-4068-bfee-5a715e21f011">

**Comment by datasherlock** [comment]
> Followed your instructions, and I end up getting the following error:
> 
> ```
> (streamlit_navbar) ~/streamlit_navbar-main $ streamlit run app_navbar.py
> Traceback (most recent call last):
>   File "/Users/cmoriarty/opt/miniconda3/envs/streamlit_navbar/bin/streamlit", line 5, in <module>
>     from streamlit.cli import main
>   File "/Users/cmoriarty/opt/miniconda3/envs/streamlit_navbar/lib/python3.7/site-packages/streamlit/__init__.py", line 48, in <module>
>     from streamlit.proto.RootContainer_pb2 import RootContainer
>   File "/Users/cmoriarty/opt/miniconda3/envs/streamlit_navbar/lib/python3.7/site-packages/streamlit/proto/RootContainer_pb2.py", line 37, in <module>
>     create_key=_descriptor._internal_create_key),
>   File "/Users/cmoriarty/opt/miniconda3/envs/streamlit_navbar/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 796, in __new__
>     _message.Message._CheckCalledFromGeneratedFile()
> TypeError: Descriptors cannot not be created directly.
> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
> If you cannot immediately regenerate your protos, some other possible workarounds are:
>  1. Downgrade the protobuf package to 3.20.x or lower.
>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
> ```
> 
> I also just copied the app's code into my own newer conda env, which did work, but doesn't actually display the top bar: <img alt="image" width="762" src="https://private-user-images.githubusercontent.com/422237/239589553-93d19a0f-cf2e-4068-bfee-5a715e21f011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNDM3NjEsIm5iZiI6MTcwMzA0MzQ2MSwicGF0aCI6Ii80MjIyMzcvMjM5NTg5NTUzLTkzZDE5YTBmLWNmMmUtNDA2OC1iZmVlLTVhNzE1ZTIxZjAxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQwMzM3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2VmMzM4YTA2Y2RjNmZiMjg4MTRiMzE3MDczOThhY2M2NzQ4YzQzMzc2ZDI2YjMzZDQyZjliYTBlNmFjZTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nuUpJizkObZOMpMF-1xwBE6iYwrYTPWLYCQZia_fY1E">

+1
